name: Build and Deploy to EC2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# ← Secrets 값을 워크플로우 env로 올려 두면 steps에서 $VAR 형태로 깔끔하게 사용 가능
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_CODE_DEPLOY_APPLICATION: ${{ secrets.AWS_CODE_DEPLOY_APPLICATION }}
  AWS_CODE_DEPLOY_GROUP: ${{ secrets.AWS_CODE_DEPLOY_GROUP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application.yml from secret
        run: |
          mkdir -p ./src/main/resources
          printf "%s" "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 테스트는 일단 건너뜀
      - name: Build (skip tests)
        run: ./gradlew clean bootJar -x test --no-daemon

      # CodeDeploy는 zip 루트에 appspec.yml이 있어야 함
      # (레포 루트에 appspec.yml이 존재한다고 가정)
      - name: Make zip bundle
        run: |
          BUNDLE="$GITHUB_SHA.zip"
          zip -r "$BUNDLE" . -x ".git/*"
          ls -lh "$BUNDLE"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.IAM_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.IAM_SECRET_KEY }}

      - name: Upload to S3
        run: aws s3 cp --region "$AWS_REGION" "$GITHUB_SHA.zip" "s3://$AWS_S3_BUCKET/$GITHUB_SHA.zip"

      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name "$AWS_CODE_DEPLOY_APPLICATION" \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name "$AWS_CODE_DEPLOY_GROUP" \
            --s3-location bucket="$AWS_S3_BUCKET",key="$GITHUB_SHA.zip",bundleType=zip